"""
ComplianceOS — MongoDB Seed Script
Seeds 90 India regulatory obligations, penalty rules, and filing templates.
Run: python db/seed_corpus.py
"""
import asyncio
import os
from datetime import datetime
from motor.motor_asyncio import AsyncIOMotorClient
from dotenv import load_dotenv

load_dotenv(dotenv_path=os.path.join(os.path.dirname(__file__), '..', '.env'))

REGULATORY_CORPUS = [
    # ── GST (15) ──────────────────────────────────────────────────────────────
    {"_id": "reg_001", "name": "GSTR-1 Monthly (Outward Supplies)", "jurisdiction": "India", "state_specific": None, "category": "taxation", "applicable_to": {"industries": ["all"], "min_turnover_inr": 5000000, "registrations_required": ["GST"], "min_employees": 0}, "frequency": "monthly", "deadline_rule": "11th of following month", "complexity": 3, "penalty_type": "financial", "imprisonment_risk": False, "depends_on": [], "last_updated": "2025-01-01", "source": "CGST Act Section 37", "max_penalty_inr": 10000},
    {"_id": "reg_002", "name": "GSTR-1 Quarterly (Outward Supplies — QRMP)", "jurisdiction": "India", "state_specific": None, "category": "taxation", "applicable_to": {"industries": ["all"], "min_turnover_inr": 0, "registrations_required": ["GST"], "min_employees": 0}, "frequency": "quarterly", "deadline_rule": "13th of month following quarter end", "complexity": 3, "penalty_type": "financial", "imprisonment_risk": False, "depends_on": [], "last_updated": "2025-01-01", "source": "CGST Act Section 37", "max_penalty_inr": 10000},
    {"_id": "reg_003", "name": "GSTR-3B Monthly (Summary Return)", "jurisdiction": "India", "state_specific": None, "category": "taxation", "applicable_to": {"industries": ["all"], "min_turnover_inr": 5000000, "registrations_required": ["GST"], "min_employees": 0}, "frequency": "monthly", "deadline_rule": "20th of following month", "complexity": 2, "penalty_type": "financial", "imprisonment_risk": False, "depends_on": ["reg_001"], "last_updated": "2025-01-01", "source": "CGST Act Section 39", "max_penalty_inr": 10000},
    {"_id": "reg_004", "name": "GSTR-3B Quarterly (QRMP scheme)", "jurisdiction": "India", "state_specific": None, "category": "taxation", "applicable_to": {"industries": ["all"], "min_turnover_inr": 0, "registrations_required": ["GST"], "min_employees": 0}, "frequency": "quarterly", "deadline_rule": "22nd/24th of month following quarter end", "complexity": 2, "penalty_type": "financial", "imprisonment_risk": False, "depends_on": ["reg_002"], "last_updated": "2025-01-01", "source": "CGST Act Section 39", "max_penalty_inr": 10000},
    {"_id": "reg_005", "name": "GSTR-9 Annual Return", "jurisdiction": "India", "state_specific": None, "category": "taxation", "applicable_to": {"industries": ["all"], "min_turnover_inr": 2000000, "registrations_required": ["GST"], "min_employees": 0}, "frequency": "annual", "deadline_rule": "31st December of following financial year", "complexity": 4, "penalty_type": "financial", "imprisonment_risk": False, "depends_on": ["reg_003", "reg_004"], "last_updated": "2025-01-01", "source": "CGST Act Section 44", "max_penalty_inr": 200000},
    {"_id": "reg_006", "name": "GSTR-9C Annual Audit Reconciliation", "jurisdiction": "India", "state_specific": None, "category": "taxation", "applicable_to": {"industries": ["all"], "min_turnover_inr": 50000000, "registrations_required": ["GST"], "min_employees": 0}, "frequency": "annual", "deadline_rule": "31st December of following financial year", "complexity": 5, "penalty_type": "financial", "imprisonment_risk": False, "depends_on": ["reg_005"], "last_updated": "2025-01-01", "source": "CGST Act Section 44", "max_penalty_inr": 500000},
    {"_id": "reg_007", "name": "GSTR-4 Composition Scheme Annual Return", "jurisdiction": "India", "state_specific": None, "category": "taxation", "applicable_to": {"industries": ["all"], "min_turnover_inr": 0, "registrations_required": ["GST"], "min_employees": 0}, "frequency": "annual", "deadline_rule": "30th April of following financial year", "complexity": 2, "penalty_type": "financial", "imprisonment_risk": False, "depends_on": [], "last_updated": "2025-01-01", "source": "CGST Act Section 10", "max_penalty_inr": 10000},
    {"_id": "reg_008", "name": "GSTR-7 TDS Return", "jurisdiction": "India", "state_specific": None, "category": "taxation", "applicable_to": {"industries": ["government", "psu"], "min_turnover_inr": 0, "registrations_required": ["GST"], "min_employees": 0}, "frequency": "monthly", "deadline_rule": "10th of following month", "complexity": 2, "penalty_type": "financial", "imprisonment_risk": False, "depends_on": [], "last_updated": "2025-01-01", "source": "CGST Act Section 51", "max_penalty_inr": 10000},
    {"_id": "reg_009", "name": "GSTR-8 TCS Return (E-commerce Operator)", "jurisdiction": "India", "state_specific": None, "category": "taxation", "applicable_to": {"industries": ["ecommerce"], "min_turnover_inr": 0, "registrations_required": ["GST"], "min_employees": 0}, "frequency": "monthly", "deadline_rule": "10th of following month", "complexity": 3, "penalty_type": "financial", "imprisonment_risk": False, "depends_on": [], "last_updated": "2025-01-01", "source": "CGST Act Section 52", "max_penalty_inr": 10000},
    {"_id": "reg_010", "name": "GST New Registration", "jurisdiction": "India", "state_specific": None, "category": "taxation", "applicable_to": {"industries": ["all"], "min_turnover_inr": 2000000, "registrations_required": [], "min_employees": 0}, "frequency": "one_time", "deadline_rule": "Within 30 days of crossing threshold", "complexity": 2, "penalty_type": "financial", "imprisonment_risk": False, "depends_on": [], "last_updated": "2025-01-01", "source": "CGST Act Section 22", "max_penalty_inr": 25000},
    {"_id": "reg_011", "name": "GST Registration Amendment", "jurisdiction": "India", "state_specific": None, "category": "taxation", "applicable_to": {"industries": ["all"], "min_turnover_inr": 0, "registrations_required": ["GST"], "min_employees": 0}, "frequency": "as_needed", "deadline_rule": "Within 15 days of change in particulars", "complexity": 1, "penalty_type": "financial", "imprisonment_risk": False, "depends_on": ["reg_010"], "last_updated": "2025-01-01", "source": "CGST Rule 19", "max_penalty_inr": 25000},
    {"_id": "reg_012", "name": "GST Letter of Undertaking (LUT) for Exporters", "jurisdiction": "India", "state_specific": None, "category": "taxation", "applicable_to": {"industries": ["all"], "min_turnover_inr": 0, "registrations_required": ["GST"], "min_employees": 0}, "frequency": "annual", "deadline_rule": "Before first export of each financial year", "complexity": 2, "penalty_type": "financial", "imprisonment_risk": False, "depends_on": ["reg_010"], "last_updated": "2025-01-01", "source": "CGST Rule 96A", "max_penalty_inr": 25000},
    {"_id": "reg_013", "name": "ITC-04 Job Work Return", "jurisdiction": "India", "state_specific": None, "category": "taxation", "applicable_to": {"industries": ["manufacturing"], "min_turnover_inr": 50000000, "registrations_required": ["GST"], "min_employees": 0}, "frequency": "half_yearly", "deadline_rule": "25th of month following half year", "complexity": 3, "penalty_type": "financial", "imprisonment_risk": False, "depends_on": ["reg_003"], "last_updated": "2025-01-01", "source": "CGST Rule 45", "max_penalty_inr": 10000},
    {"_id": "reg_014", "name": "GST Refund Application (RFD-01)", "jurisdiction": "India", "state_specific": None, "category": "taxation", "applicable_to": {"industries": ["all"], "min_turnover_inr": 0, "registrations_required": ["GST"], "min_employees": 0}, "frequency": "as_needed", "deadline_rule": "Within 2 years from relevant date", "complexity": 4, "penalty_type": "financial", "imprisonment_risk": False, "depends_on": ["reg_003"], "last_updated": "2025-01-01", "source": "CGST Section 54", "max_penalty_inr": 0},
    {"_id": "reg_015", "name": "GST Annual Aggregate Turnover Declaration", "jurisdiction": "India", "state_specific": None, "category": "taxation", "applicable_to": {"industries": ["all"], "min_turnover_inr": 0, "registrations_required": ["GST"], "min_employees": 0}, "frequency": "annual", "deadline_rule": "31st March of each financial year", "complexity": 1, "penalty_type": "financial", "imprisonment_risk": False, "depends_on": [], "last_updated": "2025-01-01", "source": "CGST Portal", "max_penalty_inr": 5000},

    # ── EPF (8) ───────────────────────────────────────────────────────────────
    {"_id": "reg_016", "name": "EPF Monthly ECR (Electronic Challan cum Return)", "jurisdiction": "India", "state_specific": None, "category": "labour", "applicable_to": {"industries": ["all"], "min_turnover_inr": 0, "registrations_required": ["EPF"], "min_employees": 20}, "frequency": "monthly", "deadline_rule": "15th of following month", "complexity": 2, "penalty_type": "financial", "imprisonment_risk": False, "depends_on": [], "last_updated": "2025-01-01", "source": "EPF Act 1952 Section 6", "max_penalty_inr": 500000},
    {"_id": "reg_017", "name": "PF Annual Return Form 3A (Member-wise)", "jurisdiction": "India", "state_specific": None, "category": "labour", "applicable_to": {"industries": ["all"], "min_turnover_inr": 0, "registrations_required": ["EPF"], "min_employees": 20}, "frequency": "annual", "deadline_rule": "30th April of following year", "complexity": 3, "penalty_type": "financial", "imprisonment_risk": True, "depends_on": ["reg_016"], "last_updated": "2025-01-01", "source": "EPF Scheme 1952 Para 35", "max_penalty_inr": 100000},
    {"_id": "reg_018", "name": "PF Annual Return Form 6A (Consolidated)", "jurisdiction": "India", "state_specific": None, "category": "labour", "applicable_to": {"industries": ["all"], "min_turnover_inr": 0, "registrations_required": ["EPF"], "min_employees": 20}, "frequency": "annual", "deadline_rule": "30th April of following year", "complexity": 3, "penalty_type": "financial", "imprisonment_risk": True, "depends_on": ["reg_016"], "last_updated": "2025-01-01", "source": "EPF Scheme 1952 Para 36", "max_penalty_inr": 100000},
    {"_id": "reg_019", "name": "EPF New Establishment Registration", "jurisdiction": "India", "state_specific": None, "category": "labour", "applicable_to": {"industries": ["all"], "min_turnover_inr": 0, "registrations_required": [], "min_employees": 20}, "frequency": "one_time", "deadline_rule": "Within 30 days of reaching 20 employees", "complexity": 2, "penalty_type": "financial", "imprisonment_risk": True, "depends_on": [], "last_updated": "2025-01-01", "source": "EPF Act 1952 Section 1(3)", "max_penalty_inr": 500000},
    {"_id": "reg_020", "name": "PF Form 11 — New Employee Declaration", "jurisdiction": "India", "state_specific": None, "category": "labour", "applicable_to": {"industries": ["all"], "min_turnover_inr": 0, "registrations_required": ["EPF"], "min_employees": 20}, "frequency": "as_needed", "deadline_rule": "Within 1 month of joining", "complexity": 1, "penalty_type": "financial", "imprisonment_risk": False, "depends_on": ["reg_019"], "last_updated": "2025-01-01", "source": "EPF Scheme Para 34B", "max_penalty_inr": 5000},
    {"_id": "reg_021", "name": "PF Form 13 — Transfer of Account", "jurisdiction": "India", "state_specific": None, "category": "labour", "applicable_to": {"industries": ["all"], "min_turnover_inr": 0, "registrations_required": ["EPF"], "min_employees": 20}, "frequency": "as_needed", "deadline_rule": "Within 30 days of employee request", "complexity": 2, "penalty_type": "financial", "imprisonment_risk": False, "depends_on": ["reg_019"], "last_updated": "2025-01-01", "source": "EPF Scheme Para 57", "max_penalty_inr": 5000},
    {"_id": "reg_022", "name": "PF Form 19 — Final Settlement on Exit", "jurisdiction": "India", "state_specific": None, "category": "labour", "applicable_to": {"industries": ["all"], "min_turnover_inr": 0, "registrations_required": ["EPF"], "min_employees": 20}, "frequency": "as_needed", "deadline_rule": "Within 30 days of exit", "complexity": 2, "penalty_type": "financial", "imprisonment_risk": False, "depends_on": ["reg_019"], "last_updated": "2025-01-01", "source": "EPF Scheme Para 69", "max_penalty_inr": 10000},
    {"_id": "reg_023", "name": "EPS Form 10C — Pension Withdrawal", "jurisdiction": "India", "state_specific": None, "category": "labour", "applicable_to": {"industries": ["all"], "min_turnover_inr": 0, "registrations_required": ["EPF"], "min_employees": 20}, "frequency": "as_needed", "deadline_rule": "Within 60 days of exit", "complexity": 2, "penalty_type": "financial", "imprisonment_risk": False, "depends_on": ["reg_019"], "last_updated": "2025-01-01", "source": "EPS 1995 Para 19", "max_penalty_inr": 5000},

    # ── ESI (6) ───────────────────────────────────────────────────────────────
    {"_id": "reg_024", "name": "ESI Monthly Contribution Payment", "jurisdiction": "India", "state_specific": None, "category": "labour", "applicable_to": {"industries": ["all"], "min_turnover_inr": 0, "registrations_required": ["ESI"], "min_employees": 10}, "frequency": "monthly", "deadline_rule": "15th of following month", "complexity": 2, "penalty_type": "financial", "imprisonment_risk": False, "depends_on": [], "last_updated": "2025-01-01", "source": "ESI Act 1948 Section 40", "max_penalty_inr": 500000},
    {"_id": "reg_025", "name": "ESI Half-Yearly Return (Form 6)", "jurisdiction": "India", "state_specific": None, "category": "labour", "applicable_to": {"industries": ["all"], "min_turnover_inr": 0, "registrations_required": ["ESI"], "min_employees": 10}, "frequency": "half_yearly", "deadline_rule": "11th November / 11th May", "complexity": 2, "penalty_type": "financial", "imprisonment_risk": True, "depends_on": ["reg_024"], "last_updated": "2025-01-01", "source": "ESI Act 1948 Section 44", "max_penalty_inr": 50000},
    {"_id": "reg_026", "name": "ESI New Establishment Registration", "jurisdiction": "India", "state_specific": None, "category": "labour", "applicable_to": {"industries": ["all"], "min_turnover_inr": 0, "registrations_required": [], "min_employees": 10}, "frequency": "one_time", "deadline_rule": "Within 15 days of reaching 10 employees", "complexity": 2, "penalty_type": "financial", "imprisonment_risk": True, "depends_on": [], "last_updated": "2025-01-01", "source": "ESI Act 1948 Section 2A", "max_penalty_inr": 25000},
    {"_id": "reg_027", "name": "ESI Accident Report (Form 16)", "jurisdiction": "India", "state_specific": None, "category": "labour", "applicable_to": {"industries": ["all"], "min_turnover_inr": 0, "registrations_required": ["ESI"], "min_employees": 10}, "frequency": "as_needed", "deadline_rule": "Within 24 hours of accident", "complexity": 1, "penalty_type": "both", "imprisonment_risk": True, "depends_on": ["reg_026"], "last_updated": "2025-01-01", "source": "ESI Act 1948 Section 44", "max_penalty_inr": 100000},
    {"_id": "reg_028", "name": "ESI Form 37 — Annual Information Return", "jurisdiction": "India", "state_specific": None, "category": "labour", "applicable_to": {"industries": ["all"], "min_turnover_inr": 0, "registrations_required": ["ESI"], "min_employees": 10}, "frequency": "annual", "deadline_rule": "31st May of following year", "complexity": 2, "penalty_type": "financial", "imprisonment_risk": False, "depends_on": ["reg_024"], "last_updated": "2025-01-01", "source": "ESI Act 1948", "max_penalty_inr": 25000},
    {"_id": "reg_029", "name": "ESI Form 40 — New Employee Registration", "jurisdiction": "India", "state_specific": None, "category": "labour", "applicable_to": {"industries": ["all"], "min_turnover_inr": 0, "registrations_required": ["ESI"], "min_employees": 10}, "frequency": "as_needed", "deadline_rule": "Within 10 days of joining", "complexity": 1, "penalty_type": "financial", "imprisonment_risk": False, "depends_on": ["reg_026"], "last_updated": "2025-01-01", "source": "ESI Regulations 1950", "max_penalty_inr": 5000},

    # ── FSSAI (6) ─────────────────────────────────────────────────────────────
    {"_id": "reg_030", "name": "FSSAI Annual Return (Form D-1)", "jurisdiction": "India", "state_specific": None, "category": "food_safety", "applicable_to": {"industries": ["food_services", "manufacturing"], "min_turnover_inr": 1200000, "registrations_required": ["FSSAI"], "min_employees": 0}, "frequency": "annual", "deadline_rule": "31st May of following year", "complexity": 2, "penalty_type": "financial", "imprisonment_risk": False, "depends_on": [], "last_updated": "2025-01-01", "source": "FSS Act 2006 Section 31", "max_penalty_inr": 500000},
    {"_id": "reg_031", "name": "FSSAI License Renewal (State/Central)", "jurisdiction": "India", "state_specific": None, "category": "food_safety", "applicable_to": {"industries": ["food_services", "manufacturing"], "min_turnover_inr": 1200000, "registrations_required": ["FSSAI"], "min_employees": 0}, "frequency": "annual", "deadline_rule": "30 days before expiry", "complexity": 3, "penalty_type": "financial", "imprisonment_risk": True, "depends_on": [], "last_updated": "2025-01-01", "source": "FSS Act 2006 Section 31", "max_penalty_inr": 500000},
    {"_id": "reg_032", "name": "FSSAI Basic Registration Renewal", "jurisdiction": "India", "state_specific": None, "category": "food_safety", "applicable_to": {"industries": ["food_services"], "min_turnover_inr": 0, "registrations_required": ["FSSAI"], "min_employees": 0}, "frequency": "annual", "deadline_rule": "30 days before expiry", "complexity": 1, "penalty_type": "financial", "imprisonment_risk": False, "depends_on": [], "last_updated": "2025-01-01", "source": "FSS Act 2006 Section 31", "max_penalty_inr": 100000},
    {"_id": "reg_033", "name": "FSSAI Food Safety Audit", "jurisdiction": "India", "state_specific": None, "category": "food_safety", "applicable_to": {"industries": ["food_services", "manufacturing"], "min_turnover_inr": 10000000, "registrations_required": ["FSSAI"], "min_employees": 0}, "frequency": "annual", "deadline_rule": "Once per financial year", "complexity": 4, "penalty_type": "both", "imprisonment_risk": True, "depends_on": ["reg_031"], "last_updated": "2025-01-01", "source": "FSS (Licensing) Regulations 2011", "max_penalty_inr": 1000000},
    {"_id": "reg_034", "name": "FSSAI Form B — License Application/Renewal", "jurisdiction": "India", "state_specific": None, "category": "food_safety", "applicable_to": {"industries": ["food_services", "manufacturing"], "min_turnover_inr": 1200000, "registrations_required": [], "min_employees": 0}, "frequency": "one_time", "deadline_rule": "Before commencing business", "complexity": 3, "penalty_type": "financial", "imprisonment_risk": True, "depends_on": [], "last_updated": "2025-01-01", "source": "FSS (Licensing) Regulations 2011", "max_penalty_inr": 500000},
    {"_id": "reg_035", "name": "FSSAI Product Recall Notice", "jurisdiction": "India", "state_specific": None, "category": "food_safety", "applicable_to": {"industries": ["food_services", "manufacturing"], "min_turnover_inr": 0, "registrations_required": ["FSSAI"], "min_employees": 0}, "frequency": "as_needed", "deadline_rule": "Within 72 hours of identifying unsafe product", "complexity": 4, "penalty_type": "both", "imprisonment_risk": True, "depends_on": ["reg_031"], "last_updated": "2025-01-01", "source": "FSS Act 2006 Section 28", "max_penalty_inr": 1000000},

    # ── Shops & Establishments (8) ────────────────────────────────────────────
    {"_id": "reg_036", "name": "Shops & Establishments Registration (Tamil Nadu)", "jurisdiction": "India", "state_specific": "Tamil Nadu", "category": "shops_establishments", "applicable_to": {"industries": ["all"], "min_turnover_inr": 0, "registrations_required": [], "min_employees": 0}, "frequency": "one_time", "deadline_rule": "Within 30 days of opening", "complexity": 1, "penalty_type": "financial", "imprisonment_risk": False, "depends_on": [], "last_updated": "2025-01-01", "source": "TN Shops Act 1947 Section 3", "max_penalty_inr": 10000},
    {"_id": "reg_037", "name": "Shops & Establishments Annual Renewal (Tamil Nadu)", "jurisdiction": "India", "state_specific": "Tamil Nadu", "category": "shops_establishments", "applicable_to": {"industries": ["all"], "min_turnover_inr": 0, "registrations_required": ["Shop_License"], "min_employees": 0}, "frequency": "annual", "deadline_rule": "31st December of each year", "complexity": 1, "penalty_type": "financial", "imprisonment_risk": False, "depends_on": ["reg_036"], "last_updated": "2025-01-01", "source": "TN Shops Act 1947 Section 4", "max_penalty_inr": 10000},
    {"_id": "reg_038", "name": "Shops & Establishments Change of Address (Tamil Nadu)", "jurisdiction": "India", "state_specific": "Tamil Nadu", "category": "shops_establishments", "applicable_to": {"industries": ["all"], "min_turnover_inr": 0, "registrations_required": ["Shop_License"], "min_employees": 0}, "frequency": "as_needed", "deadline_rule": "Within 15 days of change", "complexity": 1, "penalty_type": "financial", "imprisonment_risk": False, "depends_on": ["reg_036"], "last_updated": "2025-01-01", "source": "TN Shops Act 1947", "max_penalty_inr": 5000},
    {"_id": "reg_039", "name": "Employee Register Maintenance (Form H)", "jurisdiction": "India", "state_specific": "Tamil Nadu", "category": "shops_establishments", "applicable_to": {"industries": ["all"], "min_turnover_inr": 0, "registrations_required": ["Shop_License"], "min_employees": 1}, "frequency": "as_needed", "deadline_rule": "Updated within 3 days of each change", "complexity": 1, "penalty_type": "financial", "imprisonment_risk": True, "depends_on": ["reg_036"], "last_updated": "2025-01-01", "source": "TN Shops Act 1947 Section 15", "max_penalty_inr": 5000},
    {"_id": "reg_040", "name": "Leave Register Maintenance", "jurisdiction": "India", "state_specific": "Tamil Nadu", "category": "shops_establishments", "applicable_to": {"industries": ["all"], "min_turnover_inr": 0, "registrations_required": ["Shop_License"], "min_employees": 1}, "frequency": "as_needed", "deadline_rule": "Maintained continuously", "complexity": 1, "penalty_type": "financial", "imprisonment_risk": False, "depends_on": ["reg_036"], "last_updated": "2025-01-01", "source": "TN Shops Act 1947 Section 22", "max_penalty_inr": 2000},
    {"_id": "reg_041", "name": "Wages Register Maintenance (Form IV)", "jurisdiction": "India", "state_specific": None, "category": "shops_establishments", "applicable_to": {"industries": ["all"], "min_turnover_inr": 0, "registrations_required": [], "min_employees": 1}, "frequency": "monthly", "deadline_rule": "Updated within 3 days of wage payment", "complexity": 1, "penalty_type": "financial", "imprisonment_risk": True, "depends_on": [], "last_updated": "2025-01-01", "source": "Payment of Wages Act 1936 Section 13A", "max_penalty_inr": 10000},
    {"_id": "reg_042", "name": "Working Hours Display Board", "jurisdiction": "India", "state_specific": "Tamil Nadu", "category": "shops_establishments", "applicable_to": {"industries": ["all"], "min_turnover_inr": 0, "registrations_required": ["Shop_License"], "min_employees": 1}, "frequency": "one_time", "deadline_rule": "Displayed at all times", "complexity": 1, "penalty_type": "financial", "imprisonment_risk": False, "depends_on": ["reg_036"], "last_updated": "2025-01-01", "source": "TN Shops Act 1947 Section 7", "max_penalty_inr": 2000},
    {"_id": "reg_043", "name": "Shop Closure Notice", "jurisdiction": "India", "state_specific": "Tamil Nadu", "category": "shops_establishments", "applicable_to": {"industries": ["all"], "min_turnover_inr": 0, "registrations_required": ["Shop_License"], "min_employees": 0}, "frequency": "as_needed", "deadline_rule": "15 days prior to closing", "complexity": 1, "penalty_type": "financial", "imprisonment_risk": False, "depends_on": ["reg_036"], "last_updated": "2025-01-01", "source": "TN Shops Act 1947 Section 4", "max_penalty_inr": 5000},

    # ── Companies Act (10) ────────────────────────────────────────────────────
    {"_id": "reg_044", "name": "MGT-7 Annual Return (Companies)", "jurisdiction": "India", "state_specific": None, "category": "corporate", "applicable_to": {"industries": ["all"], "min_turnover_inr": 0, "registrations_required": [], "min_employees": 0}, "frequency": "annual", "deadline_rule": "Within 60 days of AGM (by 29th November)", "complexity": 3, "penalty_type": "financial", "imprisonment_risk": True, "depends_on": [], "last_updated": "2025-01-01", "source": "Companies Act 2013 Section 92", "max_penalty_inr": 500000},
    {"_id": "reg_045", "name": "AOC-4 Financial Statements Filing", "jurisdiction": "India", "state_specific": None, "category": "corporate", "applicable_to": {"industries": ["all"], "min_turnover_inr": 0, "registrations_required": [], "min_employees": 0}, "frequency": "annual", "deadline_rule": "Within 30 days of AGM (by 29th October)", "complexity": 4, "penalty_type": "financial", "imprisonment_risk": True, "depends_on": [], "last_updated": "2025-01-01", "source": "Companies Act 2013 Section 137", "max_penalty_inr": 1000000},
    {"_id": "reg_046", "name": "DIR-3 KYC — Director KYC", "jurisdiction": "India", "state_specific": None, "category": "corporate", "applicable_to": {"industries": ["all"], "min_turnover_inr": 0, "registrations_required": [], "min_employees": 0}, "frequency": "annual", "deadline_rule": "30th September of each year", "complexity": 1, "penalty_type": "financial", "imprisonment_risk": False, "depends_on": [], "last_updated": "2025-01-01", "source": "Companies Act 2013 Rule 12A", "max_penalty_inr": 5000},
    {"_id": "reg_047", "name": "DIR-12 Director Appointment/Resignation", "jurisdiction": "India", "state_specific": None, "category": "corporate", "applicable_to": {"industries": ["all"], "min_turnover_inr": 0, "registrations_required": [], "min_employees": 0}, "frequency": "as_needed", "deadline_rule": "Within 30 days of change", "complexity": 2, "penalty_type": "financial", "imprisonment_risk": False, "depends_on": [], "last_updated": "2025-01-01", "source": "Companies Act 2013 Section 168", "max_penalty_inr": 50000},
    {"_id": "reg_048", "name": "MGT-14 Resolution Filing", "jurisdiction": "India", "state_specific": None, "category": "corporate", "applicable_to": {"industries": ["all"], "min_turnover_inr": 0, "registrations_required": [], "min_employees": 0}, "frequency": "as_needed", "deadline_rule": "Within 30 days of passing resolution", "complexity": 2, "penalty_type": "financial", "imprisonment_risk": False, "depends_on": [], "last_updated": "2025-01-01", "source": "Companies Act 2013 Section 117", "max_penalty_inr": 500000},
    {"_id": "reg_049", "name": "INC-22 Registered Office Verification", "jurisdiction": "India", "state_specific": None, "category": "corporate", "applicable_to": {"industries": ["all"], "min_turnover_inr": 0, "registrations_required": [], "min_employees": 0}, "frequency": "one_time", "deadline_rule": "Within 30 days of incorporation", "complexity": 2, "penalty_type": "financial", "imprisonment_risk": False, "depends_on": [], "last_updated": "2025-01-01", "source": "Companies Act 2013 Section 12", "max_penalty_inr": 100000},
    {"_id": "reg_050", "name": "SH-7 Authorized Share Capital Increase", "jurisdiction": "India", "state_specific": None, "category": "corporate", "applicable_to": {"industries": ["all"], "min_turnover_inr": 0, "registrations_required": [], "min_employees": 0}, "frequency": "as_needed", "deadline_rule": "Within 30 days of resolution", "complexity": 3, "penalty_type": "financial", "imprisonment_risk": False, "depends_on": [], "last_updated": "2025-01-01", "source": "Companies Act 2013 Section 61", "max_penalty_inr": 500000},
    {"_id": "reg_051", "name": "ADT-1 Auditor Appointment", "jurisdiction": "India", "state_specific": None, "category": "corporate", "applicable_to": {"industries": ["all"], "min_turnover_inr": 0, "registrations_required": [], "min_employees": 0}, "frequency": "annual", "deadline_rule": "Within 15 days of AGM", "complexity": 2, "penalty_type": "financial", "imprisonment_risk": False, "depends_on": [], "last_updated": "2025-01-01", "source": "Companies Act 2013 Section 139", "max_penalty_inr": 300000},
    {"_id": "reg_052", "name": "MBP-1 Director Interest Disclosure", "jurisdiction": "India", "state_specific": None, "category": "corporate", "applicable_to": {"industries": ["all"], "min_turnover_inr": 0, "registrations_required": [], "min_employees": 0}, "frequency": "annual", "deadline_rule": "First Board Meeting of financial year", "complexity": 1, "penalty_type": "financial", "imprisonment_risk": False, "depends_on": [], "last_updated": "2025-01-01", "source": "Companies Act 2013 Section 184", "max_penalty_inr": 100000},
    {"_id": "reg_053", "name": "BEN-2 Beneficial Owner Declaration", "jurisdiction": "India", "state_specific": None, "category": "corporate", "applicable_to": {"industries": ["all"], "min_turnover_inr": 0, "registrations_required": [], "min_employees": 0}, "frequency": "as_needed", "deadline_rule": "Within 30 days of significant beneficial ownership", "complexity": 2, "penalty_type": "financial", "imprisonment_risk": True, "depends_on": [], "last_updated": "2025-01-01", "source": "Companies Act 2013 Section 90", "max_penalty_inr": 200000},

    # ── Labour Laws (12) ──────────────────────────────────────────────────────
    {"_id": "reg_054", "name": "Minimum Wages Register Form A", "jurisdiction": "India", "state_specific": None, "category": "labour", "applicable_to": {"industries": ["all"], "min_turnover_inr": 0, "registrations_required": [], "min_employees": 1}, "frequency": "monthly", "deadline_rule": "Updated within 3 days of wage payment", "complexity": 1, "penalty_type": "financial", "imprisonment_risk": True, "depends_on": [], "last_updated": "2025-01-01", "source": "Minimum Wages Act 1948 Section 18", "max_penalty_inr": 10000},
    {"_id": "reg_055", "name": "Muster Roll Form B", "jurisdiction": "India", "state_specific": None, "category": "labour", "applicable_to": {"industries": ["all"], "min_turnover_inr": 0, "registrations_required": [], "min_employees": 1}, "frequency": "monthly", "deadline_rule": "Updated daily", "complexity": 1, "penalty_type": "financial", "imprisonment_risk": True, "depends_on": [], "last_updated": "2025-01-01", "source": "Minimum Wages Act 1948 Section 18", "max_penalty_inr": 10000},
    {"_id": "reg_056", "name": "Wage Slip Form C", "jurisdiction": "India", "state_specific": None, "category": "labour", "applicable_to": {"industries": ["all"], "min_turnover_inr": 0, "registrations_required": [], "min_employees": 1}, "frequency": "monthly", "deadline_rule": "On or before wage payment day", "complexity": 1, "penalty_type": "financial", "imprisonment_risk": False, "depends_on": [], "last_updated": "2025-01-01", "source": "Minimum Wages Act 1948", "max_penalty_inr": 5000},
    {"_id": "reg_057", "name": "Overtime Register Form D", "jurisdiction": "India", "state_specific": None, "category": "labour", "applicable_to": {"industries": ["all"], "min_turnover_inr": 0, "registrations_required": [], "min_employees": 1}, "frequency": "monthly", "deadline_rule": "Updated on same day as overtime", "complexity": 1, "penalty_type": "financial", "imprisonment_risk": True, "depends_on": [], "last_updated": "2025-01-01", "source": "Minimum Wages Act 1948 Section 14", "max_penalty_inr": 5000},
    {"_id": "reg_058", "name": "Contract Labour Register Form XI", "jurisdiction": "India", "state_specific": None, "category": "labour", "applicable_to": {"industries": ["manufacturing", "construction"], "min_turnover_inr": 0, "registrations_required": [], "min_employees": 20}, "frequency": "as_needed", "deadline_rule": "Maintained at all times", "complexity": 2, "penalty_type": "financial", "imprisonment_risk": True, "depends_on": [], "last_updated": "2025-01-01", "source": "Contract Labour Act 1970 Section 29", "max_penalty_inr": 50000},
    {"_id": "reg_059", "name": "Contract Labour Half-Yearly Return Form XXIV", "jurisdiction": "India", "state_specific": None, "category": "labour", "applicable_to": {"industries": ["manufacturing", "construction"], "min_turnover_inr": 0, "registrations_required": [], "min_employees": 20}, "frequency": "half_yearly", "deadline_rule": "30th September / 31st March", "complexity": 2, "penalty_type": "financial", "imprisonment_risk": True, "depends_on": ["reg_058"], "last_updated": "2025-01-01", "source": "Contract Labour Act 1970", "max_penalty_inr": 50000},
    {"_id": "reg_060", "name": "Employment Card Form XIII", "jurisdiction": "India", "state_specific": None, "category": "labour", "applicable_to": {"industries": ["all"], "min_turnover_inr": 0, "registrations_required": [], "min_employees": 1}, "frequency": "as_needed", "deadline_rule": "Issued within 3 days of joining", "complexity": 1, "penalty_type": "financial", "imprisonment_risk": False, "depends_on": [], "last_updated": "2025-01-01", "source": "Minimum Wages Act 1948", "max_penalty_inr": 5000},
    {"_id": "reg_061", "name": "Annual Return — Payment of Bonus Act", "jurisdiction": "India", "state_specific": None, "category": "labour", "applicable_to": {"industries": ["all"], "min_turnover_inr": 0, "registrations_required": [], "min_employees": 20}, "frequency": "annual", "deadline_rule": "31st January of following year", "complexity": 2, "penalty_type": "financial", "imprisonment_risk": True, "depends_on": [], "last_updated": "2025-01-01", "source": "Payment of Bonus Act 1965 Section 26", "max_penalty_inr": 50000},
    {"_id": "reg_062", "name": "Maternity Benefit Register", "jurisdiction": "India", "state_specific": None, "category": "labour", "applicable_to": {"industries": ["all"], "min_turnover_inr": 0, "registrations_required": [], "min_employees": 10}, "frequency": "as_needed", "deadline_rule": "Maintained at all times when applicable", "complexity": 1, "penalty_type": "financial", "imprisonment_risk": True, "depends_on": [], "last_updated": "2025-01-01", "source": "Maternity Benefit Act 1961 Section 28", "max_penalty_inr": 50000},
    {"_id": "reg_063", "name": "Equal Remuneration Register", "jurisdiction": "India", "state_specific": None, "category": "labour", "applicable_to": {"industries": ["all"], "min_turnover_inr": 0, "registrations_required": [], "min_employees": 1}, "frequency": "as_needed", "deadline_rule": "Maintained at all times", "complexity": 1, "penalty_type": "financial", "imprisonment_risk": True, "depends_on": [], "last_updated": "2025-01-01", "source": "Equal Remuneration Act 1976 Section 8", "max_penalty_inr": 20000},
    {"_id": "reg_064", "name": "POSH — Internal Committee Constitution", "jurisdiction": "India", "state_specific": None, "category": "labour", "applicable_to": {"industries": ["all"], "min_turnover_inr": 0, "registrations_required": [], "min_employees": 10}, "frequency": "one_time", "deadline_rule": "Mandatory for all establishments with 10+ employees", "complexity": 2, "penalty_type": "financial", "imprisonment_risk": False, "depends_on": [], "last_updated": "2025-01-01", "source": "POSH Act 2013 Section 4", "max_penalty_inr": 50000},
    {"_id": "reg_065", "name": "POSH Annual Report to District Officer", "jurisdiction": "India", "state_specific": None, "category": "labour", "applicable_to": {"industries": ["all"], "min_turnover_inr": 0, "registrations_required": [], "min_employees": 10}, "frequency": "annual", "deadline_rule": "31st January of following year", "complexity": 2, "penalty_type": "financial", "imprisonment_risk": False, "depends_on": ["reg_064"], "last_updated": "2025-01-01", "source": "POSH Act 2013 Section 21", "max_penalty_inr": 50000},

    # ── Income Tax (10) ───────────────────────────────────────────────────────
    {"_id": "reg_066", "name": "TDS Return Form 24Q (Salary)", "jurisdiction": "India", "state_specific": None, "category": "taxation", "applicable_to": {"industries": ["all"], "min_turnover_inr": 0, "registrations_required": [], "min_employees": 1}, "frequency": "quarterly", "deadline_rule": "31st July / 31st October / 31st January / 31st May", "complexity": 3, "penalty_type": "financial", "imprisonment_risk": True, "depends_on": [], "last_updated": "2025-01-01", "source": "Income Tax Act 1961 Section 200", "max_penalty_inr": 100000},
    {"_id": "reg_067", "name": "TDS Return Form 26Q (Non-Salary Payments)", "jurisdiction": "India", "state_specific": None, "category": "taxation", "applicable_to": {"industries": ["all"], "min_turnover_inr": 0, "registrations_required": [], "min_employees": 0}, "frequency": "quarterly", "deadline_rule": "31st July / 31st October / 31st January / 31st May", "complexity": 3, "penalty_type": "financial", "imprisonment_risk": True, "depends_on": [], "last_updated": "2025-01-01", "source": "Income Tax Act 1961 Section 200", "max_penalty_inr": 100000},
    {"_id": "reg_068", "name": "TDS Return Form 27Q (Foreign Payments)", "jurisdiction": "India", "state_specific": None, "category": "taxation", "applicable_to": {"industries": ["all"], "min_turnover_inr": 0, "registrations_required": [], "min_employees": 0}, "frequency": "quarterly", "deadline_rule": "31st July / 31st October / 31st January / 31st May", "complexity": 4, "penalty_type": "financial", "imprisonment_risk": True, "depends_on": [], "last_updated": "2025-01-01", "source": "Income Tax Act 1961 Section 195", "max_penalty_inr": 100000},
    {"_id": "reg_069", "name": "TCS Return Form 27EQ", "jurisdiction": "India", "state_specific": None, "category": "taxation", "applicable_to": {"industries": ["all"], "min_turnover_inr": 100000000, "registrations_required": [], "min_employees": 0}, "frequency": "quarterly", "deadline_rule": "15th July / 15th October / 15th January / 15th May", "complexity": 3, "penalty_type": "financial", "imprisonment_risk": True, "depends_on": [], "last_updated": "2025-01-01", "source": "Income Tax Act 1961 Section 206C", "max_penalty_inr": 100000},
    {"_id": "reg_070", "name": "Advance Tax Q1 (15th June)", "jurisdiction": "India", "state_specific": None, "category": "taxation", "applicable_to": {"industries": ["all"], "min_turnover_inr": 0, "registrations_required": [], "min_employees": 0}, "frequency": "quarterly", "deadline_rule": "15th June (15% of estimated tax)", "complexity": 2, "penalty_type": "financial", "imprisonment_risk": False, "depends_on": [], "last_updated": "2025-01-01", "source": "Income Tax Act 1961 Section 208", "max_penalty_inr": 0},
    {"_id": "reg_071", "name": "Advance Tax Q2 (15th September)", "jurisdiction": "India", "state_specific": None, "category": "taxation", "applicable_to": {"industries": ["all"], "min_turnover_inr": 0, "registrations_required": [], "min_employees": 0}, "frequency": "quarterly", "deadline_rule": "15th September (45% cumulative)", "complexity": 2, "penalty_type": "financial", "imprisonment_risk": False, "depends_on": ["reg_070"], "last_updated": "2025-01-01", "source": "Income Tax Act 1961 Section 208", "max_penalty_inr": 0},
    {"_id": "reg_072", "name": "Advance Tax Q3 (15th December)", "jurisdiction": "India", "state_specific": None, "category": "taxation", "applicable_to": {"industries": ["all"], "min_turnover_inr": 0, "registrations_required": [], "min_employees": 0}, "frequency": "quarterly", "deadline_rule": "15th December (75% cumulative)", "complexity": 2, "penalty_type": "financial", "imprisonment_risk": False, "depends_on": ["reg_071"], "last_updated": "2025-01-01", "source": "Income Tax Act 1961 Section 208", "max_penalty_inr": 0},
    {"_id": "reg_073", "name": "Advance Tax Q4 (15th March)", "jurisdiction": "India", "state_specific": None, "category": "taxation", "applicable_to": {"industries": ["all"], "min_turnover_inr": 0, "registrations_required": [], "min_employees": 0}, "frequency": "quarterly", "deadline_rule": "15th March (100% cumulative)", "complexity": 2, "penalty_type": "financial", "imprisonment_risk": False, "depends_on": ["reg_072"], "last_updated": "2025-01-01", "source": "Income Tax Act 1961 Section 208", "max_penalty_inr": 0},
    {"_id": "reg_074", "name": "Income Tax Return — Company (ITR-6)", "jurisdiction": "India", "state_specific": None, "category": "taxation", "applicable_to": {"industries": ["all"], "min_turnover_inr": 0, "registrations_required": [], "min_employees": 0}, "frequency": "annual", "deadline_rule": "31st October (with audit) / 31st July (without)", "complexity": 5, "penalty_type": "financial", "imprisonment_risk": True, "depends_on": ["reg_073"], "last_updated": "2025-01-01", "source": "Income Tax Act 1961 Section 139", "max_penalty_inr": 10000},
    {"_id": "reg_075", "name": "Income Tax Return — Proprietorship (ITR-3/4)", "jurisdiction": "India", "state_specific": None, "category": "taxation", "applicable_to": {"industries": ["all"], "min_turnover_inr": 0, "registrations_required": [], "min_employees": 0}, "frequency": "annual", "deadline_rule": "31st July (without audit) / 31st October (with audit)", "complexity": 4, "penalty_type": "financial", "imprisonment_risk": False, "depends_on": ["reg_073"], "last_updated": "2025-01-01", "source": "Income Tax Act 1961 Section 139", "max_penalty_inr": 10000},

    # ── Fire Safety & Environment (8) ─────────────────────────────────────────
    {"_id": "reg_076", "name": "Fire NOC Annual Renewal", "jurisdiction": "India", "state_specific": "Tamil Nadu", "category": "fire_safety", "applicable_to": {"industries": ["all"], "min_turnover_inr": 0, "registrations_required": [], "min_employees": 0}, "frequency": "annual", "deadline_rule": "30 days before expiry", "complexity": 2, "penalty_type": "both", "imprisonment_risk": True, "depends_on": [], "last_updated": "2025-01-01", "source": "TN Fire Service Act 1985 Section 13", "max_penalty_inr": 500000},
    {"_id": "reg_077", "name": "Fire Extinguisher Maintenance Log", "jurisdiction": "India", "state_specific": None, "category": "fire_safety", "applicable_to": {"industries": ["all"], "min_turnover_inr": 0, "registrations_required": [], "min_employees": 0}, "frequency": "half_yearly", "deadline_rule": "Every 6 months — service and update log", "complexity": 1, "penalty_type": "financial", "imprisonment_risk": True, "depends_on": [], "last_updated": "2025-01-01", "source": "Factories Act 1948 Rule 68", "max_penalty_inr": 100000},
    {"_id": "reg_078", "name": "Factories Act Form 1 — Register of Accidents", "jurisdiction": "India", "state_specific": None, "category": "fire_safety", "applicable_to": {"industries": ["manufacturing"], "min_turnover_inr": 0, "registrations_required": [], "min_employees": 10}, "frequency": "as_needed", "deadline_rule": "Within 12 hours of any accident", "complexity": 2, "penalty_type": "both", "imprisonment_risk": True, "depends_on": [], "last_updated": "2025-01-01", "source": "Factories Act 1948 Section 88", "max_penalty_inr": 200000},
    {"_id": "reg_079", "name": "Factories Act Form 2 — Annual Return", "jurisdiction": "India", "state_specific": None, "category": "fire_safety", "applicable_to": {"industries": ["manufacturing"], "min_turnover_inr": 0, "registrations_required": [], "min_employees": 10}, "frequency": "annual", "deadline_rule": "31st January of following year", "complexity": 3, "penalty_type": "financial", "imprisonment_risk": True, "depends_on": [], "last_updated": "2025-01-01", "source": "Factories Act 1948 Section 110", "max_penalty_inr": 100000},
    {"_id": "reg_080", "name": "Consent to Operate — Air (TNPCB)", "jurisdiction": "India", "state_specific": "Tamil Nadu", "category": "environmental", "applicable_to": {"industries": ["manufacturing", "food_services"], "min_turnover_inr": 0, "registrations_required": [], "min_employees": 0}, "frequency": "annual", "deadline_rule": "30 days before expiry", "complexity": 4, "penalty_type": "both", "imprisonment_risk": True, "depends_on": [], "last_updated": "2025-01-01", "source": "Air (Prevention and Control of Pollution) Act 1981", "max_penalty_inr": 1000000},
    {"_id": "reg_081", "name": "Consent to Operate — Water (TNPCB)", "jurisdiction": "India", "state_specific": "Tamil Nadu", "category": "environmental", "applicable_to": {"industries": ["manufacturing", "food_services"], "min_turnover_inr": 0, "registrations_required": [], "min_employees": 0}, "frequency": "annual", "deadline_rule": "30 days before expiry", "complexity": 4, "penalty_type": "both", "imprisonment_risk": True, "depends_on": [], "last_updated": "2025-01-01", "source": "Water (Prevention and Control of Pollution) Act 1974", "max_penalty_inr": 1000000},
    {"_id": "reg_082", "name": "Hazardous Waste Manifest Form 9", "jurisdiction": "India", "state_specific": None, "category": "environmental", "applicable_to": {"industries": ["manufacturing"], "min_turnover_inr": 0, "registrations_required": [], "min_employees": 0}, "frequency": "as_needed", "deadline_rule": "Accompanied with each hazardous waste consignment", "complexity": 3, "penalty_type": "both", "imprisonment_risk": True, "depends_on": [], "last_updated": "2025-01-01", "source": "Hazardous Waste Rules 2016", "max_penalty_inr": 1000000},
    {"_id": "reg_083", "name": "Environmental Statement Form V", "jurisdiction": "India", "state_specific": None, "category": "environmental", "applicable_to": {"industries": ["manufacturing"], "min_turnover_inr": 50000000, "registrations_required": [], "min_employees": 0}, "frequency": "annual", "deadline_rule": "30th September of each year", "complexity": 3, "penalty_type": "financial", "imprisonment_risk": True, "depends_on": ["reg_080", "reg_081"], "last_updated": "2025-01-01", "source": "Environment (Protection) Act 1986 Rule 14", "max_penalty_inr": 500000},

    # ── Trade License & Other (7) ─────────────────────────────────────────────
    {"_id": "reg_084", "name": "Trade License Renewal — Chennai Corporation", "jurisdiction": "India", "state_specific": "Tamil Nadu", "category": "shops_establishments", "applicable_to": {"industries": ["all"], "min_turnover_inr": 0, "registrations_required": ["Trade_License"], "min_employees": 0}, "frequency": "annual", "deadline_rule": "31st March of each year", "complexity": 1, "penalty_type": "financial", "imprisonment_risk": False, "depends_on": [], "last_updated": "2025-01-01", "source": "Chennai City Municipal Corporation Act 1919", "max_penalty_inr": 25000},
    {"_id": "reg_085", "name": "Professional Tax Registration (Employer)", "jurisdiction": "India", "state_specific": "Tamil Nadu", "category": "taxation", "applicable_to": {"industries": ["all"], "min_turnover_inr": 0, "registrations_required": [], "min_employees": 1}, "frequency": "one_time", "deadline_rule": "Within 30 days of employing first person", "complexity": 1, "penalty_type": "financial", "imprisonment_risk": False, "depends_on": [], "last_updated": "2025-01-01", "source": "TN Professional Tax Act 1992", "max_penalty_inr": 5000},
    {"_id": "reg_086", "name": "Professional Tax Annual Return", "jurisdiction": "India", "state_specific": "Tamil Nadu", "category": "taxation", "applicable_to": {"industries": ["all"], "min_turnover_inr": 0, "registrations_required": [], "min_employees": 1}, "frequency": "annual", "deadline_rule": "30th April of each year", "complexity": 1, "penalty_type": "financial", "imprisonment_risk": False, "depends_on": ["reg_085"], "last_updated": "2025-01-01", "source": "TN Professional Tax Act 1992 Section 6", "max_penalty_inr": 10000},
    {"_id": "reg_087", "name": "MSME Udyam Registration", "jurisdiction": "India", "state_specific": None, "category": "corporate", "applicable_to": {"industries": ["all"], "min_turnover_inr": 0, "registrations_required": [], "min_employees": 0}, "frequency": "one_time", "deadline_rule": "Recommended within 30 days of commencing business", "complexity": 1, "penalty_type": "financial", "imprisonment_risk": False, "depends_on": [], "last_updated": "2025-01-01", "source": "MSME Development Act 2006 / Udyam Portal", "max_penalty_inr": 0},
    {"_id": "reg_088", "name": "Trademark Renewal (Form TM-R)", "jurisdiction": "India", "state_specific": None, "category": "corporate", "applicable_to": {"industries": ["all"], "min_turnover_inr": 0, "registrations_required": [], "min_employees": 0}, "frequency": "one_time", "deadline_rule": "Within 6 months before expiry (every 10 years)", "complexity": 2, "penalty_type": "financial", "imprisonment_risk": False, "depends_on": [], "last_updated": "2025-01-01", "source": "Trade Marks Act 1999 Section 25", "max_penalty_inr": 0},
    {"_id": "reg_089", "name": "Import Export Code Renewal / Update", "jurisdiction": "India", "state_specific": None, "category": "corporate", "applicable_to": {"industries": ["all"], "min_turnover_inr": 0, "registrations_required": [], "min_employees": 0}, "frequency": "annual", "deadline_rule": "Annual update by 30th June", "complexity": 1, "penalty_type": "financial", "imprisonment_risk": False, "depends_on": [], "last_updated": "2025-01-01", "source": "Foreign Trade Policy 2023", "max_penalty_inr": 10000},
    {"_id": "reg_090", "name": "DPIIT Startup India Recognition", "jurisdiction": "India", "state_specific": None, "category": "corporate", "applicable_to": {"industries": ["all"], "min_turnover_inr": 0, "registrations_required": [], "min_employees": 0}, "frequency": "one_time", "deadline_rule": "Anytime within 10 years of incorporation (recommended early)", "complexity": 2, "penalty_type": "financial", "imprisonment_risk": False, "depends_on": [], "last_updated": "2025-01-01", "source": "DPIIT Startup India Policy 2016", "max_penalty_inr": 0},
]

PENALTY_RULES = [
    {"_id": "pen_001", "regulation_id": "reg_001", "base_penalty_inr": 500, "per_day_late_inr": 50, "max_penalty_inr": 10000, "size_multipliers": {"micro": 0.5, "small": 1.0, "medium": 1.5}, "repeat_offender_factor": 1.5, "imprisonment_clause": False, "source": "CGST Act Section 47"},
    {"_id": "pen_002", "regulation_id": "reg_002", "base_penalty_inr": 500, "per_day_late_inr": 50, "max_penalty_inr": 10000, "size_multipliers": {"micro": 0.5, "small": 1.0, "medium": 1.5}, "repeat_offender_factor": 1.5, "imprisonment_clause": False, "source": "CGST Act Section 47"},
    {"_id": "pen_003", "regulation_id": "reg_003", "base_penalty_inr": 500, "per_day_late_inr": 50, "max_penalty_inr": 10000, "size_multipliers": {"micro": 0.5, "small": 1.0, "medium": 1.5}, "repeat_offender_factor": 1.5, "imprisonment_clause": False, "source": "CGST Act Section 47"},
    {"_id": "pen_004", "regulation_id": "reg_004", "base_penalty_inr": 500, "per_day_late_inr": 50, "max_penalty_inr": 10000, "size_multipliers": {"micro": 0.5, "small": 1.0, "medium": 1.5}, "repeat_offender_factor": 1.5, "imprisonment_clause": False, "source": "CGST Act Section 47"},
    {"_id": "pen_005", "regulation_id": "reg_005", "base_penalty_inr": 25000, "per_day_late_inr": 200, "max_penalty_inr": 200000, "size_multipliers": {"micro": 0.5, "small": 1.0, "medium": 1.5}, "repeat_offender_factor": 2.0, "imprisonment_clause": False, "source": "CGST Act Section 47"},
    {"_id": "pen_006", "regulation_id": "reg_006", "base_penalty_inr": 50000, "per_day_late_inr": 500, "max_penalty_inr": 500000, "size_multipliers": {"micro": 1.0, "small": 1.0, "medium": 1.5}, "repeat_offender_factor": 2.0, "imprisonment_clause": False, "source": "CGST Act Section 47"},
    {"_id": "pen_007", "regulation_id": "reg_007", "base_penalty_inr": 200, "per_day_late_inr": 50, "max_penalty_inr": 5000, "size_multipliers": {"micro": 0.5, "small": 1.0, "medium": 1.0}, "repeat_offender_factor": 1.5, "imprisonment_clause": False, "source": "CGST Act Section 47"},
    {"_id": "pen_016", "regulation_id": "reg_016", "base_penalty_inr": 5000, "per_day_late_inr": 100, "max_penalty_inr": 500000, "size_multipliers": {"micro": 1.0, "small": 1.0, "medium": 1.5}, "repeat_offender_factor": 2.0, "imprisonment_clause": False, "source": "EPF Act Section 14B — damages up to 100% of dues"},
    {"_id": "pen_017", "regulation_id": "reg_017", "base_penalty_inr": 5000, "per_day_late_inr": 200, "max_penalty_inr": 100000, "size_multipliers": {"micro": 1.0, "small": 1.0, "medium": 1.5}, "repeat_offender_factor": 2.0, "imprisonment_clause": True, "source": "EPF Act Section 14"},
    {"_id": "pen_018", "regulation_id": "reg_018", "base_penalty_inr": 5000, "per_day_late_inr": 200, "max_penalty_inr": 100000, "size_multipliers": {"micro": 1.0, "small": 1.0, "medium": 1.5}, "repeat_offender_factor": 2.0, "imprisonment_clause": True, "source": "EPF Act Section 14"},
    {"_id": "pen_024", "regulation_id": "reg_024", "base_penalty_inr": 5000, "per_day_late_inr": 100, "max_penalty_inr": 500000, "size_multipliers": {"micro": 1.0, "small": 1.0, "medium": 1.5}, "repeat_offender_factor": 1.5, "imprisonment_clause": False, "source": "ESI Act Section 85"},
    {"_id": "pen_025", "regulation_id": "reg_025", "base_penalty_inr": 5000, "per_day_late_inr": 100, "max_penalty_inr": 50000, "size_multipliers": {"micro": 1.0, "small": 1.0, "medium": 1.5}, "repeat_offender_factor": 2.0, "imprisonment_clause": True, "source": "ESI Act Section 85"},
    {"_id": "pen_030", "regulation_id": "reg_030", "base_penalty_inr": 5000, "per_day_late_inr": 100, "max_penalty_inr": 500000, "size_multipliers": {"micro": 1.0, "small": 1.0, "medium": 1.5}, "repeat_offender_factor": 2.0, "imprisonment_clause": False, "source": "FSS Act Section 55"},
    {"_id": "pen_031", "regulation_id": "reg_031", "base_penalty_inr": 25000, "per_day_late_inr": 500, "max_penalty_inr": 500000, "size_multipliers": {"micro": 1.0, "small": 1.0, "medium": 2.0}, "repeat_offender_factor": 3.0, "imprisonment_clause": True, "source": "FSS Act Section 63"},
    {"_id": "pen_036", "regulation_id": "reg_036", "base_penalty_inr": 1000, "per_day_late_inr": 50, "max_penalty_inr": 10000, "size_multipliers": {"micro": 0.5, "small": 1.0, "medium": 1.0}, "repeat_offender_factor": 1.5, "imprisonment_clause": False, "source": "TN Shops Act Section 33"},
    {"_id": "pen_037", "regulation_id": "reg_037", "base_penalty_inr": 1000, "per_day_late_inr": 50, "max_penalty_inr": 10000, "size_multipliers": {"micro": 0.5, "small": 1.0, "medium": 1.0}, "repeat_offender_factor": 1.5, "imprisonment_clause": False, "source": "TN Shops Act Section 33"},
    {"_id": "pen_044", "regulation_id": "reg_044", "base_penalty_inr": 50000, "per_day_late_inr": 100, "max_penalty_inr": 500000, "size_multipliers": {"micro": 1.0, "small": 1.0, "medium": 1.5}, "repeat_offender_factor": 2.0, "imprisonment_clause": True, "source": "Companies Act Section 92"},
    {"_id": "pen_045", "regulation_id": "reg_045", "base_penalty_inr": 100000, "per_day_late_inr": 100, "max_penalty_inr": 1000000, "size_multipliers": {"micro": 1.0, "small": 1.0, "medium": 1.5}, "repeat_offender_factor": 2.0, "imprisonment_clause": True, "source": "Companies Act Section 137"},
    {"_id": "pen_046", "regulation_id": "reg_046", "base_penalty_inr": 5000, "per_day_late_inr": 0, "max_penalty_inr": 5000, "size_multipliers": {"micro": 1.0, "small": 1.0, "medium": 1.0}, "repeat_offender_factor": 1.0, "imprisonment_clause": False, "source": "Companies Act Rule 12A"},
    {"_id": "pen_054", "regulation_id": "reg_054", "base_penalty_inr": 500, "per_day_late_inr": 0, "max_penalty_inr": 10000, "size_multipliers": {"micro": 1.0, "small": 1.0, "medium": 1.5}, "repeat_offender_factor": 2.0, "imprisonment_clause": True, "source": "Minimum Wages Act Section 22A"},
    {"_id": "pen_066", "regulation_id": "reg_066", "base_penalty_inr": 10000, "per_day_late_inr": 200, "max_penalty_inr": 100000, "size_multipliers": {"micro": 1.0, "small": 1.0, "medium": 1.5}, "repeat_offender_factor": 2.0, "imprisonment_clause": True, "source": "Income Tax Act Section 271H"},
    {"_id": "pen_067", "regulation_id": "reg_067", "base_penalty_inr": 10000, "per_day_late_inr": 200, "max_penalty_inr": 100000, "size_multipliers": {"micro": 1.0, "small": 1.0, "medium": 1.5}, "repeat_offender_factor": 2.0, "imprisonment_clause": True, "source": "Income Tax Act Section 271H"},
    {"_id": "pen_074", "regulation_id": "reg_074", "base_penalty_inr": 5000, "per_day_late_inr": 0, "max_penalty_inr": 10000, "size_multipliers": {"micro": 1.0, "small": 1.0, "medium": 1.0}, "repeat_offender_factor": 1.0, "imprisonment_clause": True, "source": "Income Tax Act Section 276CC"},
    {"_id": "pen_076", "regulation_id": "reg_076", "base_penalty_inr": 10000, "per_day_late_inr": 500, "max_penalty_inr": 500000, "size_multipliers": {"micro": 1.0, "small": 1.0, "medium": 2.0}, "repeat_offender_factor": 3.0, "imprisonment_clause": True, "source": "TN Fire Service Act 1985"},
    {"_id": "pen_084", "regulation_id": "reg_084", "base_penalty_inr": 1000, "per_day_late_inr": 50, "max_penalty_inr": 25000, "size_multipliers": {"micro": 0.5, "small": 1.0, "medium": 1.0}, "repeat_offender_factor": 1.5, "imprisonment_clause": False, "source": "Chennai Municipal Corporation Act"},
    {"_id": "pen_086", "regulation_id": "reg_086", "base_penalty_inr": 250, "per_day_late_inr": 0, "max_penalty_inr": 10000, "size_multipliers": {"micro": 1.0, "small": 1.0, "medium": 1.0}, "repeat_offender_factor": 1.5, "imprisonment_clause": False, "source": "TN Professional Tax Act Section 12"},
]

FILING_TEMPLATES = [
    {"_id": "tmpl_001", "regulation_id": "reg_003", "template_name": "GSTR-3B Monthly Return", "fields": [{"field_name": "gstin", "maps_to": "businesses.registrations.GST"}, {"field_name": "legal_name", "maps_to": "businesses.name"}, {"field_name": "period", "maps_to": "obligation_instances.period"}, {"field_name": "state_code", "maps_to": "businesses.state"}, {"field_name": "outward_taxable_value", "maps_to": "computed_from_invoices"}, {"field_name": "tax_payable_igst", "maps_to": "computed_from_rate_and_value"}, {"field_name": "tax_payable_cgst", "maps_to": "computed_from_rate_and_value"}, {"field_name": "tax_payable_sgst", "maps_to": "computed_from_rate_and_value"}], "output_format": "json", "authority_portal": "https://www.gst.gov.in"},
    {"_id": "tmpl_002", "regulation_id": "reg_001", "template_name": "GSTR-1 Monthly Outward Supplies", "fields": [{"field_name": "gstin", "maps_to": "businesses.registrations.GST"}, {"field_name": "legal_name", "maps_to": "businesses.name"}, {"field_name": "period", "maps_to": "obligation_instances.period"}, {"field_name": "aggregate_turnover", "maps_to": "businesses.annual_turnover_inr"}], "output_format": "json", "authority_portal": "https://www.gst.gov.in"},
    {"_id": "tmpl_003", "regulation_id": "reg_016", "template_name": "EPF ECR Monthly Challan", "fields": [{"field_name": "establishment_code", "maps_to": "businesses.registrations.EPF"}, {"field_name": "establishment_name", "maps_to": "businesses.name"}, {"field_name": "wage_month", "maps_to": "obligation_instances.period"}, {"field_name": "total_employees", "maps_to": "businesses.employee_count"}, {"field_name": "total_epf_wages", "maps_to": "computed_from_payroll"}, {"field_name": "employer_share_pf", "maps_to": "computed_from_payroll"}, {"field_name": "employee_share_pf", "maps_to": "computed_from_payroll"}], "output_format": "pdf", "authority_portal": "https://unifiedportal-emp.epfindia.gov.in"},
    {"_id": "tmpl_004", "regulation_id": "reg_024", "template_name": "ESI Monthly Contribution Challan", "fields": [{"field_name": "employer_code", "maps_to": "businesses.registrations.ESI"}, {"field_name": "employer_name", "maps_to": "businesses.name"}, {"field_name": "contribution_period", "maps_to": "obligation_instances.period"}, {"field_name": "total_employees_covered", "maps_to": "businesses.employee_count"}, {"field_name": "total_wages", "maps_to": "computed_from_payroll"}, {"field_name": "employer_contribution", "maps_to": "computed_from_payroll"}, {"field_name": "employee_contribution", "maps_to": "computed_from_payroll"}], "output_format": "pdf", "authority_portal": "https://www.esic.in"},
    {"_id": "tmpl_005", "regulation_id": "reg_030", "template_name": "FSSAI Annual Return Form D-1", "fields": [{"field_name": "license_number", "maps_to": "businesses.registrations.FSSAI"}, {"field_name": "name_of_fbo", "maps_to": "businesses.name"}, {"field_name": "address", "maps_to": "businesses.city"}, {"field_name": "state", "maps_to": "businesses.state"}, {"field_name": "annual_turnover", "maps_to": "businesses.annual_turnover_inr"}, {"field_name": "products_manufactured", "maps_to": "businesses.industry"}], "output_format": "pdf", "authority_portal": "https://foscos.fssai.gov.in"},
    {"_id": "tmpl_006", "regulation_id": "reg_044", "template_name": "MGT-7 Annual Return (Companies)", "fields": [{"field_name": "cin", "maps_to": "businesses.registrations.CIN"}, {"field_name": "company_name", "maps_to": "businesses.name"}, {"field_name": "registered_office_address", "maps_to": "businesses.city"}, {"field_name": "financial_year", "maps_to": "obligation_instances.period"}, {"field_name": "paid_up_capital", "maps_to": "businesses.annual_turnover_inr"}, {"field_name": "turnover", "maps_to": "businesses.annual_turnover_inr"}], "output_format": "pdf", "authority_portal": "https://www.mca.gov.in"},
    {"_id": "tmpl_007", "regulation_id": "reg_067", "template_name": "TDS Return Form 26Q", "fields": [{"field_name": "tan", "maps_to": "businesses.registrations.TAN"}, {"field_name": "deductor_name", "maps_to": "businesses.name"}, {"field_name": "quarter", "maps_to": "obligation_instances.period"}, {"field_name": "financial_year", "maps_to": "obligation_instances.period"}, {"field_name": "total_amount_paid", "maps_to": "computed_from_payments"}, {"field_name": "total_tds_deducted", "maps_to": "computed_from_payments"}], "output_format": "fvu", "authority_portal": "https://www.tdscpc.gov.in"},
    {"_id": "tmpl_008", "regulation_id": "reg_070", "template_name": "Advance Tax Challan ITNS 280", "fields": [{"field_name": "pan", "maps_to": "businesses.registrations.PAN"}, {"field_name": "assessment_year", "maps_to": "obligation_instances.period"}, {"field_name": "taxpayer_name", "maps_to": "businesses.name"}, {"field_name": "amount", "maps_to": "computed_from_estimated_tax"}, {"field_name": "installment_type", "maps_to": "obligation_instances.period"}], "output_format": "pdf", "authority_portal": "https://www.incometax.gov.in"},
    {"_id": "tmpl_009", "regulation_id": "reg_086", "template_name": "Professional Tax Annual Return", "fields": [{"field_name": "pt_enrolment_no", "maps_to": "businesses.registrations.PT"}, {"field_name": "employer_name", "maps_to": "businesses.name"}, {"field_name": "financial_year", "maps_to": "obligation_instances.period"}, {"field_name": "number_of_employees", "maps_to": "businesses.employee_count"}, {"field_name": "total_pt_collected", "maps_to": "computed_from_payroll"}], "output_format": "pdf", "authority_portal": "https://www.tnstax.gov.in"},
    {"_id": "tmpl_010", "regulation_id": "reg_084", "template_name": "Trade License Renewal — Chennai", "fields": [{"field_name": "license_number", "maps_to": "businesses.registrations.Trade_License"}, {"field_name": "business_name", "maps_to": "businesses.name"}, {"field_name": "owner_name", "maps_to": "businesses.owner"}, {"field_name": "address", "maps_to": "businesses.city"}, {"field_name": "business_type", "maps_to": "businesses.business_type"}, {"field_name": "renewal_year", "maps_to": "obligation_instances.period"}], "output_format": "pdf", "authority_portal": "https://www.chennaicorporation.gov.in"},
]


async def main():
    load_dotenv(dotenv_path=os.path.join(os.path.dirname(__file__), '..', '.env'))
    uri = os.getenv("MONGODB_URI", "")
    db_name = os.getenv("MONGODB_DB_NAME", "complianceos")

    if not uri:
        print("ERROR: MONGODB_URI not set in .env")
        return

    print(f"Connecting to MongoDB Atlas...")
    client = AsyncIOMotorClient(uri)
    db = client[db_name]

    print("Dropping existing collections...")
    for coll in ["regulatory_corpus", "penalty_rules", "filing_templates",
                 "businesses", "obligation_instances", "regulatory_changes",
                 "filing_history", "agent_decisions"]:
        await db[coll].drop()

    print("Inserting regulatory_corpus...")
    result = await db.regulatory_corpus.insert_many(REGULATORY_CORPUS)
    print(f"  ✅ {len(result.inserted_ids)} regulations inserted")

    print("Inserting penalty_rules...")
    result = await db.penalty_rules.insert_many(PENALTY_RULES)
    print(f"  ✅ {len(result.inserted_ids)} penalty rules inserted")

    print("Inserting filing_templates...")
    result = await db.filing_templates.insert_many(FILING_TEMPLATES)
    print(f"  ✅ {len(result.inserted_ids)} filing templates inserted")

    print("Creating indexes...")
    await db.regulatory_corpus.create_index([("category", 1)])
    await db.regulatory_corpus.create_index([("applicable_to.industries", 1)])
    await db.regulatory_corpus.create_index([("applicable_to.min_employees", 1)])
    await db.obligation_instances.create_index([("business_id", 1), ("status", 1)])
    await db.obligation_instances.create_index([("business_id", 1), ("decay_score", 1)])
    await db.agent_decisions.create_index([("business_id", 1), ("timestamp", -1)])

    print(f"\n🎉 Seed complete. {len(REGULATORY_CORPUS)} regulations | {len(PENALTY_RULES)} penalty rules | {len(FILING_TEMPLATES)} templates")
    client.close()


if __name__ == "__main__":
    asyncio.run(main())
